# -*- coding: utf-8 -*-
"""664244112

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSCbf3tCImnmFUO2LwWj5WG9eLfVliTu
"""

# ฟังก์ชันสำหรับแต่ละค่าความจริง
def implication(p, q):
    return not p or q

def converse(p, q):
    return not q or p

def contrapositive(p, q):
    return not q or not p

def inverse(p, q):
    return not p or not q

# แสดงหัวตาราง
print(f"{'P':^5} {'Q':^5} {'P -> Q':^10} {'Converse':^10} {'Contrapositive':^15} {'Inverse':^10}")

# สร้างตารางค่าความจริง
for p in [True, False]:
    for q in [True, False]:
        p_implied_q = implication(p, q)
        p_converse_q = converse(p, q)
        p_contrapositive_q = contrapositive(p, q)
        p_inverse_q = inverse(p, q)

        # แสดงผลในรูปแบบตาราง
        print(f"{p:^5} {q:^5} {p_implied_q:^10} {p_converse_q:^10} {p_contrapositive_q:^15} {p_inverse_q:^10}")